### ISSUE TITLE
Add documentation of the app

### ISSUE THREAD

**Issue by rasacharjee** [rasacharjee/poolRota#7]
Create a detailed documentation as exactly what does the app perform. 
There should be detailed explanation of what is performed when any button is pressed , which activity it moves ,what information is taken and stored.

Do study privacy policy and make a privacy policy of the app to be used for production level

**Comment by jaskirankaur51** [comment]
The documentation has been done, but will be updated with time.

**Comment by ghost** [comment]
Documentation will be made in time

**Comment by ghost** [comment]
[poolrota.docx](https://github.com/rasacharjee/poolRota/files/4587686/poolrota.docx)
